// <auto-generated />
using System;
using AIHelperNET.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIHelperNET.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608144500_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("AIHelperNET.Domain.Sessions.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AudioSource")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EndedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("AIHelperNET.Domain.Sessions.Session", b =>
                {
                    b.OwnsMany("AIHelperNET.Domain.Sessions.ConversationTurn", "ConversationTurns", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ClarificationQuestionIdsJson")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT")
                                .HasDefaultValue("[]")
                                .HasColumnName("ClarificationQuestionIds");

                            b1.Property<string>("ClarificationResponseIdsJson")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT")
                                .HasDefaultValue("[]")
                                .HasColumnName("ClarificationResponseIds");

                            b1.Property<long>("CreatedAt")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("InitialQuestionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("InitialQuestionText")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT");

                            b1.Property<int>("LastUpdateReason")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(0);

                            b1.Property<string>("QuestionFragmentsJson")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT")
                                .HasDefaultValue("[]")
                                .HasColumnName("QuestionFragments");

                            b1.Property<Guid>("SessionId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Status")
                                .HasColumnType("INTEGER");

                            b1.Property<long>("UpdatedAt")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("SessionId");

                            b1.ToTable("ConversationTurn");

                            b1.WithOwner()
                                .HasForeignKey("SessionId");

                            b1.OwnsMany("AIHelperNET.Domain.Sessions.AnswerVersion", "AnswerVersions", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("ConversationTurnId")
                                        .HasColumnType("TEXT");

                                    b2.Property<long>("CreatedAt")
                                        .HasColumnType("INTEGER");

                                    b2.Property<Guid?>("SupersedesId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .IsRequired()
                                        .HasMaxLength(32000)
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("VersionType")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("Id");

                                    b2.HasIndex("ConversationTurnId");

                                    b2.ToTable("AnswerVersion");

                                    b2.WithOwner()
                                        .HasForeignKey("ConversationTurnId");
                                });

                            b1.Navigation("AnswerVersions");
                        });

                    b.OwnsMany("AIHelperNET.Domain.Sessions.DetectedQuestion", "Questions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<long>("DetectedAt")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("SessionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("SessionId");

                            b1.ToTable("DetectedQuestion");

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.OwnsMany("AIHelperNET.Domain.Sessions.GeneratedAnswer", "Answers", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<long?>("CompletedAt")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasMaxLength(32000)
                                .HasColumnType("TEXT")
                                .HasColumnName("Content");

                            b1.Property<Guid>("QuestionId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("SessionId")
                                .HasColumnType("TEXT");

                            b1.Property<long>("StartedAt")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Status")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("SessionId");

                            b1.ToTable("GeneratedAnswer");

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.OwnsMany("AIHelperNET.Domain.Sessions.TranscriptItem", "Transcript", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<int>("BoundaryRole")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(0);

                            b1.Property<Guid>("SessionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("TEXT");

                            b1.Property<long>("Timestamp")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("SessionId");

                            b1.ToTable("TranscriptItem");

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.OwnsOne("AIHelperNET.Domain.ValueObjects.AnswerSettings", "AnswerSettings", b1 =>
                        {
                            b1.Property<Guid>("SessionId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Complexity")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Format")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Length")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("OutputLanguage")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<int>("Style")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Tone")
                                .HasColumnType("INTEGER");

                            b1.HasKey("SessionId");

                            b1.ToTable("Sessions");

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.OwnsOne("AIHelperNET.Domain.ValueObjects.CodeProfile", "CodeProfile", b1 =>
                        {
                            b1.Property<Guid>("SessionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ArchitectureStyle")
                                .HasColumnType("TEXT");

                            b1.Property<string>("BackendFramework")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CloudDevOps")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CustomNotes")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Database")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FrontendFramework")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Messaging")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ProgrammingLanguage")
                                .HasColumnType("TEXT");

                            b1.Property<string>("TestingFramework")
                                .HasColumnType("TEXT");

                            b1.HasKey("SessionId");

                            b1.ToTable("Sessions");

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.Navigation("AnswerSettings")
                        .IsRequired();

                    b.Navigation("Answers");

                    b.Navigation("CodeProfile")
                        .IsRequired();

                    b.Navigation("ConversationTurns");

                    b.Navigation("Questions");

                    b.Navigation("Transcript");
                });
#pragma warning restore 612, 618
        }
    }
}
