namespace AIHelperNET.Domain.Sessions;

/// <summary>
/// Reason for updating an existing conversation turn.
/// </summary>
public enum TurnUpdateReason
{
    /// <summary>The initial question is complete and an answer can be generated.</summary>
    InitialQuestionComplete = 0,

    /// <summary>A continuation segment adds to an in-progress question.</summary>
    ContinuationAdded,

    /// <summary>A clarification segment provides additional context for the current question.</summary>
    ClarificationAdded,

    /// <summary>An additional requirement adds a new constraint to the already-answered question.</summary>
    RequirementAdded,

    /// <summary>The answer was manually regenerated by the user.</summary>
    ManualRegeneration
}
